owner: coreeng
repo: cecg-status

sites:
  - name: cecg.io
    url: https://cecg.io/livez
  - name: Core Platform
    url: https://coreplatform.io/livez
  - name: Community
    url: https://community.cecg.io/livez
  - name: Osterley
    url: https://osterley.cecg.io/livez

status-website:
  baseUrl: /cecg-status
  name: CECG Status
  introTitle: CECG Status
  introMessage: Real-time status for CECG core platform applications.
  theme: light
  logoUrl: https://raw.githubusercontent.com/coreeng/cecg-status/master/assets/logo.png
  themeUrl: https://raw.githubusercontent.com/coreeng/cecg-status/master/assets/brand.css
  customHeadHtml: '<link rel="icon" type="image/x-icon" href="https://raw.githubusercontent.com/coreeng/cecg-status/master/assets/favicon.ico">'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/coreeng/cecg-status
